### ISSUE TITLE
protoc-gen-go-tag: breaks reflection

### ISSUE THREAD

**Issue by powerman** [searKing/golang#3] opened 2020-12-23 00:24 UTC
I've successfully used protoc-gen-go-tag to update `*.pb.go`, but then I found it somehow breaks reflection (https://google.golang.org/grpc/reflection):

```
$ grpcui localhost:11102
Failed to compute set of methods to expose: Symbol not found: comp.proj.auth.AdminAuthSvc
caused by: File not found: github.com/searKing/golang/tools/cmd/protoc-gen-go-tag/tag/tag.proto
```

Any idea how to provide this file to make it available for reflection?

**Comment by powerman** [comment] 2020-12-23 00:47
The possible workaround is to generate protoset file and provide it to `grpcui -protoset`.

**Comment by searKing** [comment] 2021-01-05 13:21
Have you tried to set the path to a directory from which proto sources can be imported, using -proto (and maybe -import-path) flags?
[Nodejs supporting](https://github.com/fullstorydev/grpcui/issues/55#issuecomment-552979320)

**Comment by searKing** [comment] 2021-01-06 03:34
Duplicate of https://github.com/fullstorydev/grpcui/issues/55#issuecomment-552979320

**Closed by searKing** 2021-01-06 03:34 UTC

**Comment by searKing** [comment] 2021-01-06 06:35
Another way is to [embedded tag.proto into your proto directly, avoid include the `tag.proto`](https://github.com/searKing/golang/tree/master/tools/cmd/protoc-gen-go-tag#trick-embedded-tagproto-into-your-proto-directly-avoid-include-the-tagproto)
